
import { 
  Trophy, 
  Users, 
  BookOpen, 
  Heart, 
  Vote, 
  Target,
  Briefcase,
  Award,
  Star,
  Zap,
  Flag,
  Gift,
  Home,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  MessageCircle,
  MessageSquare,
  Send,
  ThumbsUp,
  CheckCircle,
  AlertCircle,
  Info,
  Settings,
  Shield,
  Lock,
  Eye,
  Edit,
  Trash,
  Plus,
  Minus,
  Search,
  Filter,
  Download,
  Upload,
  Share,
  Save,
  GraduationCap,
  type LucideIcon
} from 'lucide-react';

export type { LucideIcon };

export const iconMap: { [key: string]: LucideIcon } = {
  Trophy,
  Users,
  BookOpen,
  Heart,
  Vote,
  Target,
  Briefcase,
  Award,
  Star,
  Zap,
  Flag,
  Gift,
  Home,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  MessageCircle,
  MessageSquare,
  Send,
  ThumbsUp,
  CheckCircle,
  AlertCircle,
  Info,
  Settings,
  Shield,
  Lock,
  Eye,
  Edit,
  Trash,
  Plus,
  Minus,
  Search,
  Filter,
  Download,
  Upload,
  Share,
  Save,
  GraduationCap
};

export const availableIcons = [
  { value: "Trophy", label: "Trophy 🏆" },
  { value: "Users", label: "Users 👥" },
  { value: "Heart", label: "Heart ❤️" },
  { value: "BookOpen", label: "Book 📖" },
  { value: "Vote", label: "Vote 🗳️" },
  { value: "Target", label: "Target 🎯" },
  { value: "Briefcase", label: "Briefcase 💼" },
  { value: "Award", label: "Award 🏅" },
  { value: "Star", label: "Star ⭐" },
  { value: "Zap", label: "Zap ⚡" },
  { value: "Flag", label: "Flag 🚩" },
  { value: "Gift", label: "Gift 🎁" },
  { value: "Home", label: "Home 🏠" },
  { value: "Mail", label: "Mail 📧" },
  { value: "Phone", label: "Phone 📱" },
  { value: "MapPin", label: "Location 📍" },
  { value: "Calendar", label: "Calendar 📅" },
  { value: "Clock", label: "Clock 🕐" },
  { value: "MessageCircle", label: "Message 💬" },
  { value: "MessageSquare", label: "Message Square 💬" },
  { value: "Send", label: "Send 📤" },
  { value: "ThumbsUp", label: "Thumbs Up 👍" },
  { value: "CheckCircle", label: "Check ✅" },
  { value: "AlertCircle", label: "Alert ⚠️" },
  { value: "Info", label: "Info ℹ️" },
  { value: "Settings", label: "Settings ⚙️" },
  { value: "Shield", label: "Shield 🛡️" },
  { value: "Lock", label: "Lock 🔒" },
  { value: "Eye", label: "Eye 👁️" },
  { value: "Edit", label: "Edit ✏️" },
  { value: "Trash", label: "Trash 🗑️" },
  { value: "Plus", label: "Plus ➕" },
  { value: "Minus", label: "Minus ➖" },
  { value: "Search", label: "Search 🔍" },
  { value: "Filter", label: "Filter 🔽" },
  { value: "Download", label: "Download ⬇️" },
  { value: "Upload", label: "Upload ⬆️" },
  { value: "Share", label: "Share 🔗" },
  { value: "Save", label: "Save 💾" },
  { value: "GraduationCap", label: "Graduation Cap 🎓" }
];

export const getIcon = (iconName: string): LucideIcon => {
  return iconMap[iconName] || Users; 
};

export const iconExists = (iconName: string): boolean => {
  return iconName in iconMap;
};